name: Workflow approval
on:
    workflow_dispatch:
jobs:
    first:
        environment: dev
        name: First job
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello, world!"

    second:
        environment: pre
        name: Second job
        runs-on: ubuntu-latest
        needs: first
        steps:
            - run: echo "Hello, world!"
    
    third:
        environment: pro
        name: Third job
        runs-on: ubuntu-latest
        needs: second
        steps:
            - run: echo "Hello, world!"